"""Add Google OAuth fields to AppSettings

Revision ID: ade1ee3daa21
Revises: 
Create Date: 2025-11-06 07:01:53.641255

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ade1ee3daa21'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('app_settings', sa.Column('google_user_email', sa.String(length=255), nullable=True))
    op.add_column('app_settings', sa.Column('google_user_name', sa.String(length=255), nullable=True))
    op.add_column('app_settings', sa.Column('google_user_picture', sa.Text(), nullable=True))
    op.add_column('app_settings', sa.Column('google_user_id', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('app_settings', 'google_user_id')
    op.drop_column('app_settings', 'google_user_picture')
    op.drop_column('app_settings', 'google_user_name')
    op.drop_column('app_settings', 'google_user_email')
    # ### end Alembic commands ###
